pipeline {
    agent none
    options { skipDefaultCheckout() }
    stages {
		stage ('Checkout') {
			steps {
				echo 'This is a minimal pipeline for test Assessment'
				echo 'Checking out SCM'
				checkout scm

				sh '''
					echo "PATH = ${PATH}"
					echo "M2_HOME = ${M2_HOME}"
					echo "JAVA_HOME = ${JAVA_HOME}"
					java -version
				'''
			}
		}
		stage('Build') {
			
			steps {
				echo 'Building..'
				echo 'Set JAVA_HOME to /usr/lib/jvm/java-8-openjdk-amd64 '
				sh 'export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 && mvn clean install && mvn package'
			}
		}
		stage ('Java Tests') {
			
			steps {
				echo 'Place holder to run Unit tests.'
				sh ''
				sh 'sleep 3'
			}
		}

    }
}
